name: Publish Website

on:
  push:
    branches: [ master ]
  schedule:
    - cron: "0 */6 * * *" # Run every 6 hours

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout sources
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Checkout documentation
      run: npm run clone-docs

    - name: Build project
      run: npm run build

    - name: Deploy website
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
        force_orphan: true

